### ISSUE TITLE
Story/usecase for SCSS theming variable usage

### ISSUE THREAD

**Issue by intellix** [nekkon/angular-cli-library#3]
So I was ripping my hair out over this the last day or so and have now found a solution for injecting app/brand specific variables into shared components.

You have a component called Header that you want to share across apps like so:
```ts
@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit { ... }
```

It has a SCSS file, which uses variables for things like colouring/spacing:
```scss
@import 'src/scss/variables';

:host {
  display: block;
  padding: $spacer-y $spacer-x;
  background: $bg;
}

```

...But now you realise that those variables were not brand/app specific and you need to be able to override those based on the app/brand. I've found that you can achieve this like:

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "apps": [
    {
      "name": "coca-cola",
      "stylePreprocessorOptions": {
        "includePaths": [
          "coca-cola/scss"
        ]
      },
    },
    {
      "name": "pepsi",
      "stylePreprocessorOptions": {
        "includePaths": [
          "pepsi/scss"
        ]
      },
    }
  ]
}
```

Now you just change the import references throughout to: 
```scss
@import 'scss/variables';
```

And now depending on the app you're serving, the variables change inside your base/shared components

**Comment by nekkon** [comment]
Thanks a lot for sharing. I have added this to the wiki section: [wiki](https://github.com/nekkon/angular-cli-library/wiki/SCSS-theming-with-variables-(by-@intellix-)) . I will close this issue, as it is not something considered outstanding. If anyone wants to add or change something feel free to comment here.
