### ISSUE TITLE
Module Formats

### ISSUE THREAD

**Issue by chrisalexander55** [nekkon/angular-cli-library#4]
First of all this is the best stab I've seen to date to support an Angular library. Congrats!

I have more question than issue... Any plans to support multiple module formats (UMD, FESM, ES6) of shared artifacts in build, beyond just @sharing assets? I work at a large corp and need to support a mix of dev teams - all of whom are a pain in the *ss as it relates to adopting and adhering to UI standards and component reuse. Thanks!

**Comment by nekkon** [comment]
Hello @chrisalexander55. Thanks for your kind words. Angular-cli-library supports sharing of modules also, not only assets. That means you can have code in your shared library (components in modules) and share it between apps. 

1. If you don't want your components to go online (npm publish):
You can create various branches for a repo based on this setup. For example:

- One branch could be your dev branch for creating the components. 
- Another branch could be the production branch of your components (stable) but are consumed by apps. So basically it is the development branch of your apps.
- Last branch is your production branch of your apps.

With this setup you can share locally/privately components made by your team, but also have a team creating apps based on your components.

2. If you don't mind having your components go online, then create a package.json in your module's directory and use npm publish to publish them. You can import them afterwards in your apps. There is a nice tutorial to help you out. [tutorial](https://www.tsmean.com/articles/how-to-write-a-typescript-library/angular/)

Hope I have answered your question.
