### ISSUE TITLE
Example for Shared Module lazy-loading

### ISSUE THREAD

**Issue by intellix** [nekkon/angular-cli-library#5]
Hey, thought I'd follow up in this repository so I don't pollute the other thread :)

I'm not seeing an example of the SharedModule lazy-loading anything which you said it was doing and is supported. Here is the only module inside Shared: https://github.com/nekkon/angular-cli-library/blob/master/src/shared/components/angular-cli/angular-cli.module.ts

Here's an example of what I have: https://github.com/intellix/angular-cli-library/blob/master/src/core/core-routing.module.ts

With it being included inside a blue/red app: https://github.com/intellix/angular-cli-library/blob/master/src/red/app/app.module.ts#L14

**Comment by nekkon** [comment]
@intellix I have updated the repo with an example (Example2) showcasing what you requested. :) Hope it is what you are looking for.

**Comment by intellix** [comment]
Great, thanks so much :) It seems the secret sauce was adding the core/shared directories to the `tsconfig.app1.json` `include` array
